print("Hello, Git!")
print("I am learning Git and GitHub.")
print("Git is starting to make sense.")
print("I am learning how developers use Git.")
print("My first GitHub project is coming together.")
